package Parte2;

// Enumerado para los distintos tipos de mensajes
public enum Tipo {
	SOLICITACONEXION, CONFIRMACONEXION, SOLICITALISTAUSUARIOS, CONFIRMALISTAUSUARIOS,
	PEDIRFICHERO, EMITIRFICHERO, PREPARADOCLIENTESERVIDOR,  PREPARADOSERVIDORCLIENTE,
	CERRARCONEXION, CONFIRMACIERRE, FICHEROSINPROPIETARIO
	
}
